name: webscrape_workflow #name of workflow

on: #triggered when...
  push: #a push if performed on...
    branches: #the branches with assigned name...
      - "main" #"main" (the main branch)

jobs: 
  build:
    runs-on: python-latest
    steps:
     -
      name: Checkout
      uses: actions/checkout@v3
     -
      name: Login to Docker Hub
      uses: docker/login-actions@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-actions@v2
     -
      name: Build and push
      uses: docker/build-push-actions@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/imdb-webscrape:latest
